import type { ParseSettings } from "@/lib";

export const HISTORY_KEY = "txt-wwew-tech-history";
export const HISTORY_META_KEY = "txt-wwew-tech-history-meta";
export const UI_PREFS_KEY = "txt-wwew-tech-ui-prefs";

export const defaultSettings: ParseSettings = {
  ignoredDirectories: ["node_modules", ".next", ".git", "dist", "build", ".cache", "venv", "__pycache__", "obj", "bin"],
  excludedExtensions: ["pyc", "map", "lock", "exe", "dll", "bin", "dat", "iso", "img"],
};

export const i18n = {
  ru: {
    settings: "Настройки",
    settingsSubtitle: "Панель инструментов",
    openRight: "Открыть правую панель",
    closeRight: "Скрыть правую панель",
    quickPrompts: "Быстрые подсказки",
    filter: "Фильтр...",
    parser: "Парсер",
    privacy: "Приватность",
    output: "Результат",
    activity: "Активность",
    pipeline: "Пайплайн",
    workspace: "Рабочая область",
    nothingFound: "Ничего не найдено",
    noActions: "Действий пока нет",
    includePrompt: "Включать промпт",
    showSkipped: "Показывать пропущенные",
    anonymous: "Анонимный чат",
    ignoredDirs: "Игнорировать папки",
    excludedExt: "Исключить расширения",
    build: "Собрать",
    draft: "Черновик",
    autosave: "Автосейв",
    modeChat: "Чат",
    modeStream: "Поток",
    modeRealtime: "Реалтайм",
    markdownOn: "Markdown ВКЛ",
    raw: "Сырой",
    visible: "видимые",
    selected: "выбрано",
    skipped: "пропущено",
    buildSelected: "Собрать выбранное",
    remove: "Удалить",
    processing: "Обработка файлов...",
    parserReady: "Готов",
    parserProcessing: "Обработка",
    builderReady: "Контекст готов",
    builderWaiting: "Ожидание",
    historyEntries: "записей",
    sources: "Источники",
    files: "Файлы",
    size: "Размер",
    tokens: "Токены",
    tokenSuffix: "токенов",
    theme: "Тема",
    terms: "Условия",
    newChat: "Новый чат",
    history: "История",
    noEntries: "Записей пока нет",
    actions: "Действия",
    source: "Источник",
    makeCopy: "Сделать копию",
    share: "Поделиться",
    rename: "Переименовать",
    copyPrompt: "Копировать промпт",
    copyFinal: "Копировать итог",
    delete: "Удалить",
    builderTitle: "Сборщик LLM-контекста",
    promptPlaceholder: "Добавьте инструкцию для LLM...",
    uploadFiles: "Файлы",
    uploadFolder: "Папка",
    save: "Сохранить",
    downloadTxt: "Скачать .txt",
    parsing: "Парсинг файлов...",
    preview: "Превью",
    finalTxt: "Итоговый LLM-ready TXT",
    addFilesToSee: "Добавьте файлы, чтобы увидеть итоговый контекст.",
    dropHint: "Перетащи файлы, архивы или папки сюда, чтобы построить единый LLM-ready контекст.",
    localCockpit: "Локальный контекст-кокпит",
    typingPlaceholder: "Введите сообщение…",
    send: "Отправить",
    you: "Вы",
    contextEngine: "Контекст-движок",
    fileCount: "файлов",
    folderCount: "папок",
    archiveParsed: "Архив распарсен",
    folderStructure: "Структура папки",
    singleFile: "Одиночный файл",
    previewAction: "Предпросмотр",
    download: "Скачать",
    edit: "Изменить",
    searchHint: "Поиск по имени или пути файла",
    sortDefault: "По умолчанию",
    sortName: "Имя",
    sortTokens: "Токены",
    sortSize: "Размер",
    close: "Закрыть",
    closeChat: "Закрыть чат",
    draftChat: "Новый чат (черновик)",
    down: "Вниз",
    noData: "Нет данных",
    editContextTitle: "Изменить контекст",
    renameChatTitle: "Новое название чата",
    editPlaceholder: "Введите новый контекст...",
    renamePlaceholder: "Введите название чата...",
    cancel: "Отмена",
    display: "Отображение",
    uiScale: "Масштаб UI",
    uiScaleCompact: "Компакт",
    uiScaleDefault: "По умолчанию",
    uiScaleLarge: "Крупный",
    fontSizeLabel: "Размер шрифта",
    compactModeLabel: "Компактный режим",
  },
  en: {
    settings: "Settings",
    settingsSubtitle: "Tool cockpit",
    openRight: "Open right sidebar",
    closeRight: "Hide right sidebar",
    quickPrompts: "Quick Prompts",
    filter: "Filter...",
    parser: "Parser",
    privacy: "Privacy",
    output: "Output",
    activity: "Activity",
    pipeline: "Pipeline",
    workspace: "Workspace",
    nothingFound: "Nothing found",
    noActions: "No actions yet",
    includePrompt: "Include prompt",
    showSkipped: "Show skipped",
    anonymous: "Anonymous chat",
    ignoredDirs: "Ignore directories",
    excludedExt: "Excluded extensions",
    build: "Build",
    draft: "Draft",
    autosave: "Autosave",
    modeChat: "Chat",
    modeStream: "Stream",
    modeRealtime: "Realtime",
    markdownOn: "Markdown ON",
    raw: "Raw",
    visible: "visible",
    selected: "selected",
    skipped: "skipped",
    buildSelected: "Build selected",
    remove: "Remove",
    processing: "Processing files...",
    parserReady: "Ready",
    parserProcessing: "Processing",
    builderReady: "Context ready",
    builderWaiting: "Waiting",
    historyEntries: "entries",
    sources: "Sources",
    files: "Files",
    size: "Size",
    tokens: "Tokens",
    tokenSuffix: "tokens",
    theme: "Theme",
    terms: "Terms",
    newChat: "New chat",
    history: "History",
    noEntries: "No entries yet",
    actions: "Actions",
    source: "Source",
    makeCopy: "Duplicate",
    share: "Share",
    rename: "Rename",
    copyPrompt: "Copy prompt",
    copyFinal: "Copy final",
    delete: "Delete",
    builderTitle: "LLM Context Builder",
    promptPlaceholder: "Add instruction for LLM...",
    uploadFiles: "Files",
    uploadFolder: "Folder",
    save: "Save",
    downloadTxt: "Download .txt",
    parsing: "Parsing files...",
    preview: "Preview",
    finalTxt: "Final LLM-ready TXT",
    addFilesToSee: "Add files to see final context.",
    dropHint: "Drop files, archives, or folders here to build a unified LLM-ready context.",
    localCockpit: "Local Context Cockpit",
    typingPlaceholder: "Type something…",
    send: "Send",
    you: "You",
    contextEngine: "Context Engine",
    fileCount: "files",
    folderCount: "folders",
    archiveParsed: "Archive parsed",
    folderStructure: "Folder structure",
    singleFile: "Single file",
    previewAction: "Preview",
    download: "Download",
    edit: "Edit",
    searchHint: "Search by file name or path",
    sortDefault: "Default",
    sortName: "Name",
    sortTokens: "Tokens",
    sortSize: "Size",
    close: "Close",
    closeChat: "Close chat",
    draftChat: "New chat (draft)",
    down: "Down",
    noData: "No data",
    editContextTitle: "Edit context",
    renameChatTitle: "New chat title",
    editPlaceholder: "Enter updated context...",
    renamePlaceholder: "Enter chat title...",
    cancel: "Cancel",
    display: "Display",
    uiScale: "UI Scale",
    uiScaleCompact: "Compact",
    uiScaleDefault: "Default",
    uiScaleLarge: "Large",
    fontSizeLabel: "Font size",
    compactModeLabel: "Compact mode",
  },
} as const;

export type I18nDict = { [K in keyof (typeof i18n)["en"]]: string };
