name: Update Draft Release Notes

on:
  push:
    branches:
      - main
      - master
  pull_request:
    types: [closed]

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4
      - uses: release-drafter/release-drafter@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-name: release-drafter.yml
